### ISSUE TITLE
Eklenti Libre Office 5.3'e kurulamiyor.

### ISSUE THREAD

**Issue by mdakin** [COMU/zemberek-extension#19]
5.3 versiyonuna kurmaya calisinca asagidaki hatayi aldim. Libre Office 6.0 da calisiyor.

[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.NoClassDefFoundError: com/sun/star/linguistic2/XSpellChecker
java stack trace:
java.lang.NoClassDefFoundError: com/sun/star/linguistic2/XSpellChecker
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:817)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:53)
at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:376)
Caused by: java.lang.ClassNotFoundException: com.sun.star.linguistic2.XSpellChecker
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 15 more

**Comment by ahmetaa** [comment]
Bunun iki nedeni olabilir
1- Ubuntu içerisinde bulunan LO 5 ile jar dosyaları gelmiyor ( /usr/lib/libreoffice/program/classes içerisinde projedeki lib/lo/ altındaki jar dosyaları var mı kontrol edilebilir.)
2- LO 5 ile 6'daki jar dosyalarındaki sınıflar farklı. Bu problemli bir konu olur bizim için.

**Comment by ahmetaa** [comment]
@talhakanyilmaz ve @okanozdemir Acaba Ubuntu 16.04 ile kurulu gelen LO 5 ile bir deneme yapmanız mümkün mü?

**Comment by mdakin** [comment]
Denemeyi debian tabanli bir sistemde yapmistim.

ls /usr/lib/libreoffice/program/classes
java_uno.jar  juh.jar  jurt.jar  ridl.jar  unoloader.jar

Ancak bu dosyalar LO 6 yi kurunca mi geldi bilmiyorum.

**Comment by ahmetaa** [comment]
https://askubuntu.com/questions/595286/installation-of-libreoffice-extention-of-language-tool-is-error
ve 
https://askubuntu.com/questions/458240/unable-to-install-languagetool-2-5-extension-for-libreoffice-4-2-on-ubuntu-14-04 

`sudo apt-get installlibreoffice-java-common` öneriliyor

Belki Ubuntu ve Debian ile default kurulan LO ile jarlar olmayabilir. Bunu muhtemelen kurulum dokümanına yazmalıyız.

**Comment by ahmetaa** [comment]
Evdeki taşınabilir bilgisayarda da aynı sorun çıktı. Kurulum dokümanı sorunlar kısmına bu konuyu ekledim. Bunun bir çaresi belki LO jarlarını da dağıtıma eklemek olabilir ama bu defa da zaten jar dosyaları varsa sorun çıkabilir.

**Comment by ahmetaa** [comment]
Bu sürüm artık çok kullanılmadığından ve çözüm için doküman yazıldığından kapatıyorum.
